### ISSUE TITLE
Node-cron not found

### ISSUE THREAD

**Issue by tlrwagner** [Frankity/Ps4Rpc#1]
when running I got `node-cron not found` adding that to the package.json dependencies fixed it

**Comment by thatJARED** [comment]
Do you think you could explain the solution a little more? Having a similar issue. :/

**Comment by franz3x8** [comment]
@thatJARED 

got to termnial 

type cd /Users/mac's username/Documents/GitHub/Ps4Rpc

then run npm install --save node-cron

**Comment by Frankity** [comment]
i forgot add it, sorry.
